### ISSUE TITLE
Can't start demo site locally

### ISSUE THREAD

**Issue by GetTaxSolutions** [ihym/ngx-card#10]
We cloned this project and invoke:
npm install
npm run demo

But there is many errors in the console:

> ERROR in [at-loader] ./node_modules/@types/babel-types/index.d.ts:1517:41
>     TS2304: Cannot find name 'object'.
> 
> ERROR in [at-loader] ./node_modules/@types/babel-types/index.d.ts:1517:56
>     TS2304: Cannot find name 'object'.
> 
> ERROR in [at-loader] ./node_modules/@types/babel-types/index.d.ts:1518:46
>     TS2304: Cannot find name 'object'.
> 
> ERROR in [at-loader] ./node_modules/@types/babel-types/index.d.ts:1518:61
>     TS2304: Cannot find name 'object'.
> 
> ERROR in [at-loader] ./node_modules/@types/babel-types/index.d.ts:1519:42
>     TS2304: Cannot find name 'object'.

**Comment by ihym** [comment]
The best way to see your changes in action, is to use our demo page locally. Run:
```bash
npm run demo
```
which will create a development server accessible through `http:localhost:1111`.
In conjunction with `npm start` in another command tab you have a fully working environment!

**Comment by derobiom** [comment]
Was this ever resolved?

**Comment by ihym** [comment]
Please read my comment above, carefully.
