### ISSUE TITLE
ion-input not work with ngx-card

### ISSUE THREAD

**Issue by Renanmacedo** [ihym/ngx-card#13]
This plugin not work with ion-input. You have fix to this? 
Error: Template parse errors:
Can't bind to 'name' since it isn't a known property of 'ion-input'.
1. If 'ion-input' is an Angular component and it has 'name' input, then verify that it is part of this module.
2. If 'ion-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
Thanks!

**Comment by rafaneri** [comment]
Same problem here.

**Comment by kygoh** [comment]
Managed to fix for ion-input by making changes to inputs.ts and card.ts.

inputs.ts
```javascript
import { Directive, ElementRef, Attribute } from '@angular/core';
import { uniqueId } from './util';

@Directive({
	selector: '[card-number]',
})
export class NgxCardNumberTemplate {
	constructor(public elementRef: ElementRef, @Attribute('name') public name: string) {}

	ngOnInit() {
		this.name = this.name || uniqueId('number');
		if (!this.elementRef.nativeElement.name) {
			this.elementRef.nativeElement.setAttribute("name", this.name);
		}
	}
}

@Directive({
	selector: '[card-name]',
})
export class NgxCardNameTemplate {
	constructor(public elementRef: ElementRef, @Attribute('name') public name: string) {}

	ngOnInit() {
		this.name = this.name || uniqueId('name');
		if (!this.elementRef.nativeElement.name) {
			this.elementRef.nativeElement.setAttribute("name", this.name);
		}
	}
}

@Directive({
	selector: '[card-expiry]',
})
export class NgxCardExpiryTemplate {
	constructor(public elementRef: ElementRef, @Attribute('name') public name: string) {}

	ngOnInit() {
		this.name = this.name || uniqueId('expiry');
		if (!this.elementRef.nativeElement.name) {
			this.elementRef.nativeElement.setAttribute("name", this.name);
		}
	}
}

@Directive({
	selector: '[card-cvc]',
})
export class NgxCardCvcTemplate {
	constructor(public elementRef: ElementRef, @Attribute('name') public name: string) {}

	ngOnInit() {
		this.name = this.name || uniqueId('cvc');
		if (!this.elementRef.nativeElement.name) {
			this.elementRef.nativeElement.setAttribute("name", this.name);
		}
	}
}
```
card.ts
```javascript
import { Directive, Input, ContentChildren, QueryList, ElementRef } from '@angular/core';
import { NgxCardNumberTemplate, NgxCardNameTemplate, NgxCardExpiryTemplate, NgxCardCvcTemplate } from './inputs';

declare var Card;

const defaultPlaceholders = {
	number: '•••• •••• •••• ••••',
	name: 'Full Name',
	expiry: '••/••',
	cvc: '•••',
};

const defaultMessages = {
	validDate: 'valid\nthru',
	monthYear: 'month/year',
};

@Directive({
  selector: '[card]'
})
export class NgxCard {

	// a selector or DOM element for the container
	// where you want the card to appear
	@Input() container: any;

	@Input('card-width') width: number; // optional — default 350px

	// Strings for translation - optional
	_messages;
	@Input() set messages(_messages: any) {
		this._messages = Object.assign({}, defaultMessages, _messages);
	}
	get messages() {
		return this._messages;
	}

	// Default placeholders for rendered fields - optional
	_placeholders;
	@Input() set placeholders(_placeholders: any) {
		this._placeholders = Object.assign({}, defaultPlaceholders, _placeholders);
	}
	get placeholders() {
		return this._placeholders;
	}

	@Input() masks: any;

	@Input() formatting: boolean = true; // optional - default true

	// if true, will log helpful messages for setting up Card
	@Input() debug: boolean = false; // optional - default false

	@ContentChildren(NgxCardNumberTemplate,  {descendants: true}) numbers: QueryList<NgxCardNumberTemplate>;
	@ContentChildren(NgxCardNameTemplate,  {descendants: true}) names: QueryList<NgxCardNameTemplate>;
	@ContentChildren(NgxCardExpiryTemplate,  {descendants: true}) expiries: QueryList<NgxCardExpiryTemplate>;
	@ContentChildren(NgxCardCvcTemplate,  {descendants: true}) cvcs: QueryList<NgxCardCvcTemplate>;

	constructor(private element: ElementRef) {}

	ngAfterViewInit() {
		console.log("NgxCardIonicDirective::ngAfterViewInit()");
		console.dir(this.element);
		new Card({
			form: this.element.nativeElement,
			container: this.container,
			width: this.width,
			formSelectors: {
				numberInput: this.findInputSelectors(this.numbers),
				expiryInput: this.findInputSelectors(this.expiries),
				cvcInput: this.findInputSelectors(this.cvcs),
				nameInput: this.findInputSelectors(this.names),
			},
			formatting: this.formatting,
			messages: this.messages,
			placeholders: this.placeholders,
			masks: this.masks,
			debug: this.debug,
		});
	}
/*
	findSelectors(list: QueryList<any>): string {
		return list.map(template => template.elementRef.nativeElement.tagName.toLowerCase() + '[name="' + template.name + '"]').join(', ');
	}
*/
	findInputSelectors(list: QueryList<any>): string {
		return list.map(template => `input[name="${template.name}"]`).join(', ');
	}

};
```

**Comment by mitidiero** [comment]
@kygoh can you explain why that change made it working with the ionic input? I'm asking because it is not working with reactive forms, and I'd like to find a solution.

**Comment by kygoh** [comment]
The changes to input.ts in line [6-8](https://github.com/ihym/ngx-card/blob/5003a311109e050aadefc80e6258f8b4e45b43de/src/inputs.ts#L6), [20-22](https://github.com/ihym/ngx-card/blob/5003a311109e050aadefc80e6258f8b4e45b43de/src/inputs.ts#L20), [34-36](https://github.com/ihym/ngx-card/blob/5003a311109e050aadefc80e6258f8b4e45b43de/src/inputs.ts#L34), [48-50](https://github.com/ihym/ngx-card/blob/5003a311109e050aadefc80e6258f8b4e45b43de/src/inputs.ts#L48) were made because `<ion-input>` does not support `name` attribute.

The changes to card.ts in line [67-70](https://github.com/ihym/ngx-card/blob/5003a311109e050aadefc80e6258f8b4e45b43de/src/card.ts#L67) were made to use a different [`findSelectors`](https://github.com/ihym/ngx-card/blob/5003a311109e050aadefc80e6258f8b4e45b43de/src/card.ts#L80) function.

I suspect the original [`findSelectors`](https://github.com/ihym/ngx-card/blob/5003a311109e050aadefc80e6258f8b4e45b43de/src/card.ts#L80) function will look for `ion-input` tag which couldn't work because card.js only works on `<input>` element.

I changed the [`findSelectors`](https://github.com/ihym/ngx-card/blob/5003a311109e050aadefc80e6258f8b4e45b43de/src/card.ts#L80) to look specifically for `input` tag by hardcoding the `input` tag name.

**Comment by nitr0x11** [comment]
> Managed to fix for ion-input by making changes to inputs.ts and card.ts.
> 
> inputs.ts
> 
> ```js
> import { Directive, ElementRef, Attribute } from '@angular/core';
> import { uniqueId } from './util';
> 
> @Directive({
> 	selector: '[card-number]',
> })
> export class NgxCardNumberTemplate {
> 	constructor(public elementRef: ElementRef, @Attribute('name') public name: string) {}
> 
> 	ngOnInit() {
> 		this.name = this.name || uniqueId('number');
> 		if (!this.elementRef.nativeElement.name) {
> 			this.elementRef.nativeElement.setAttribute("name", this.name);
> 		}
> 	}
> }
> 
> @Directive({
> 	selector: '[card-name]',
> })
> export class NgxCardNameTemplate {
> 	constructor(public elementRef: ElementRef, @Attribute('name') public name: string) {}
> 
> 	ngOnInit() {
> 		this.name = this.name || uniqueId('name');
> 		if (!this.elementRef.nativeElement.name) {
> 			this.elementRef.nativeElement.setAttribute("name", this.name);
> 		}
> 	}
> }
> 
> @Directive({
> 	selector: '[card-expiry]',
> })
> export class NgxCardExpiryTemplate {
> 	constructor(public elementRef: ElementRef, @Attribute('name') public name: string) {}
> 
> 	ngOnInit() {
> 		this.name = this.name || uniqueId('expiry');
> 		if (!this.elementRef.nativeElement.name) {
> 			this.elementRef.nativeElement.setAttribute("name", this.name);
> 		}
> 	}
> }
> 
> @Directive({
> 	selector: '[card-cvc]',
> })
> export class NgxCardCvcTemplate {
> 	constructor(public elementRef: ElementRef, @Attribute('name') public name: string) {}
> 
> 	ngOnInit() {
> 		this.name = this.name || uniqueId('cvc');
> 		if (!this.elementRef.nativeElement.name) {
> 			this.elementRef.nativeElement.setAttribute("name", this.name);
> 		}
> 	}
> }
> ```
> 
> card.ts
> 
> ```js
> import { Directive, Input, ContentChildren, QueryList, ElementRef } from '@angular/core';
> import { NgxCardNumberTemplate, NgxCardNameTemplate, NgxCardExpiryTemplate, NgxCardCvcTemplate } from './inputs';
> 
> declare var Card;
> 
> const defaultPlaceholders = {
> 	number: '•••• •••• •••• ••••',
> 	name: 'Full Name',
> 	expiry: '••/••',
> 	cvc: '•••',
> };
> 
> const defaultMessages = {
> 	validDate: 'valid\nthru',
> 	monthYear: 'month/year',
> };
> 
> @Directive({
>   selector: '[card]'
> })
> export class NgxCard {
> 
> 	// a selector or DOM element for the container
> 	// where you want the card to appear
> 	@Input() container: any;
> 
> 	@Input('card-width') width: number; // optional — default 350px
> 
> 	// Strings for translation - optional
> 	_messages;
> 	@Input() set messages(_messages: any) {
> 		this._messages = Object.assign({}, defaultMessages, _messages);
> 	}
> 	get messages() {
> 		return this._messages;
> 	}
> 
> 	// Default placeholders for rendered fields - optional
> 	_placeholders;
> 	@Input() set placeholders(_placeholders: any) {
> 		this._placeholders = Object.assign({}, defaultPlaceholders, _placeholders);
> 	}
> 	get placeholders() {
> 		return this._placeholders;
> 	}
> 
> 	@Input() masks: any;
> 
> 	@Input() formatting: boolean = true; // optional - default true
> 
> 	// if true, will log helpful messages for setting up Card
> 	@Input() debug: boolean = false; // optional - default false
> 
> 	@ContentChildren(NgxCardNumberTemplate,  {descendants: true}) numbers: QueryList<NgxCardNumberTemplate>;
> 	@ContentChildren(NgxCardNameTemplate,  {descendants: true}) names: QueryList<NgxCardNameTemplate>;
> 	@ContentChildren(NgxCardExpiryTemplate,  {descendants: true}) expiries: QueryList<NgxCardExpiryTemplate>;
> 	@ContentChildren(NgxCardCvcTemplate,  {descendants: true}) cvcs: QueryList<NgxCardCvcTemplate>;
> 
> 	constructor(private element: ElementRef) {}
> 
> 	ngAfterViewInit() {
> 		console.log("NgxCardIonicDirective::ngAfterViewInit()");
> 		console.dir(this.element);
> 		new Card({
> 			form: this.element.nativeElement,
> 			container: this.container,
> 			width: this.width,
> 			formSelectors: {
> 				numberInput: this.findInputSelectors(this.numbers),
> 				expiryInput: this.findInputSelectors(this.expiries),
> 				cvcInput: this.findInputSelectors(this.cvcs),
> 				nameInput: this.findInputSelectors(this.names),
> 			},
> 			formatting: this.formatting,
> 			messages: this.messages,
> 			placeholders: this.placeholders,
> 			masks: this.masks,
> 			debug: this.debug,
> 		});
> 	}
> /*
> 	findSelectors(list: QueryList<any>): string {
> 		return list.map(template => template.elementRef.nativeElement.tagName.toLowerCase() + '[name="' + template.name + '"]').join(', ');
> 	}
> */
> 	findInputSelectors(list: QueryList<any>): string {
> 		return list.map(template => `input[name="${template.name}"]`).join(', ');
> 	}
> 
> };
> ```

Hello, I am have changed the code as specified above but having no luck adding it to ion-input.

MyPage.module
import { CardModule } from '../../packages/ngx-card/ngx-card'
  imports: [
...
    CardModule,  
  ],


page.html
    ion-input type="text" name="number" card-number></ion-input>
    ion-input type="text" name="first-name" card-name></ion-input>
    ion-input type="text" name="last-name" card-name></ion-input>
    ion-input type="text" name="expiry" card-expiry></ion-input>
    ion-input type="text" name="cvc" card-cvc></ion-input>


But I am getting errors in the console saying:
card.js:148 Card can't find a numberInput in your form.
card.js:148 Card can't find a nameInput in your form.
etc.....


Are you able to assist?

**Comment by Renanmacedo** [comment]
This issus has  be fixed. Thanks!

**Comment by Renanmacedo** [comment]
This issus has  be fixed. Thanks!
