### ISSUE TITLE
Angular 9 - Build Problem

### ISSUE THREAD

**Issue by hugohcn** [ihym/ngx-card#21]
Hello there,

I updated my project from Angular 8.1 to Angular 9. I followed all the steps and instructions from the Angular.io website, however when I run **_ng build_**, I got this error:

<img width="1398" alt="Captura de Tela 2020-03-11 às 14 57 18" src="https://user-images.githubusercontent.com/6969705/76449313-9befde00-63aa-11ea-8aa2-bef3f63ac308.png">

Note: If I maintain the import on my module file, **_ng build_** works fine. If I add **_CardModule_** into **_imports_**, **_ng build_** does not work.

Can you guys help me?

Thanks!

**Comment by hugohcn** [comment]
Hey, I just fixed the address of imports on ngx-card/module.d.ts file.

After this, **_ng build_** and **_ng build --prod_** worked again.

Changed from
`import * as ɵngcc1 from './card'; import * as ɵngcc2 from './inputs';`

To

`import * as ɵngcc1 from 'ngx-card/card'; import * as ɵngcc2 from 'ngx-card/inputs';`

**Comment by eduibrahim** [comment]
Hi @hugohcn ! It works fine. No more compilation error. But when I am running the app I got: 

"Cannot read property 'id' of undefined at registerNgModuleType"

I see in other forums that it is related to the module incompatibility with Angular 9 Ivy.

Did you face something similar?

**Comment by jcarloTA** [comment]
Hi, same problem with "Cannot read property 'id' of undefined"  at registerNgModuleType"

**Comment by JunyaoC** [comment]
Yes. I have this exact same problem too. "Cannot read property 'id' of undefined" at registerNgModuleType". Any solution?

**Comment by hugohcn** [comment]
Hey guys,

@carloscpossa solved the problem just creating a new wrapper for card.js. This lib can be compiled with angular 9 project that has IVY enabled.

The directiveies are the same, so, we didn't problems to migrate to this new lib.

[ng9-card](https://www.npmjs.com/package/ng9-card)

Solved!

**Comment by eloyleonardo** [comment]
Did anyone find a solution for the `Cannot read property 'id' of undefined` ?
