### ISSUE TITLE
How to update the card image dynamically?

### ISSUE THREAD

**Issue by dmitry-grinko** [ihym/ngx-card#5]
I try to set data using reactive forms. I added formGroup
`<form [formGroup]="rForm"  (ngSubmit)="addCard(rForm.value)" ...`
and  this is my input
`<input type="text" class="form-control" formControlName="card_number" card-number>`
and this is my component
```
this.rForm = fb.group({
    'card_number': ['123', Validators.required]
});

...

addCard(val: any) {
    console.log(val);
}
```
I get {card_number: "123"} in my console by clicking addCard.
My question -Why can not I see 123 on card image? I can see only dots. 
How to update the card image?

**Comment by dmitry-grinko** [comment]
I was trying

        (<FormControl>this.rForm.get('card_number')).setValue('1212', {
            onlySelf: true,
            emitEvent: true,
            emitModelToViewChange: true,
            emitViewToModelChange: true
        });

But it doesn't help

**Comment by muneer-memon** [comment]
i have similar problem, I have card name but it doesn't populate on card image unless i press any key on that input. 
i tried firing the keyboardevent  in manually but it doesn't help
`
@ViewChild('cardOwnerName') cardOwnerName: ElementRef;

ngAfterViewInit() {
const event = new KeyboardEvent('keypress', {bubbles: true, 'key': 'Enter'});
this.cardOwnerName.nativeElement.dispatchEvent(event);
}`

any solutions?

**Comment by muneer-memon** [comment]
found the solution.
add [placeholders]="{name:cardOwnerName}" to display it on card image

**Comment by syedirfan7** [comment]
@muneer-memon 

i am able to populate the all the values dynamically  but unable to get the css for visa/master card / any type of card it just comes blank card 

![image](https://user-images.githubusercontent.com/6966314/56469488-18f32b80-6458-11e9-89d4-5f3cf6a62f29.png)

if i place focus on any input text and then move the focus somewhere else it gets the actual css.
Is there any programmatical way to deal with it ? 
thanks in advance.

**Comment by Sahil624** [comment]
Could not fill data using the placeholder. Did anyone found any other solution?

**Comment by jrbuniel15** [comment]
This how I did it programmatically:

I added #cardNumberInput tag on my card-number input field and on my .ts file I declared it as such
`@ViewChild('cardNumberInput', {static: false}) private cardNumberInput: ElementRef;`

After setting the value for the card number, I added this line of code to simulate key press on the card-number input field
`let event = new KeyboardEvent('keyup', {'bubbles':true});`
`this.cardNumberInput.nativeElement.dispatchEvent(event);`

I also had to do the same thing for the other fields so they show properly on the card, but remember to do it after setting the value.
